In [1]:
import numpy as np


In [2]:
arr=np.array([11,22,33,44,55])


In [3]:
print(arr)


[11 22 33 44 55]


In [4]:
print(type(arr))


<class 'numpy.ndarray'>


In [5]:
arr=np.array(42)


In [6]:
print(arr)


42


In [7]:
arr=np.array([11,22,33,44,55])
print(arr)


[11 22 33 44 55]


In [8]:
arr=np.array([[[10,20,30],[40,50,60],[70,80,90]]])
print(arr)


[[[10 20 30]
  [40 50 60]
  [70 80 90]]]


In [9]:
arr=np.array([[10,20,30],[40,50,60]])
print(arr)


[[10 20 30]
 [40 50 60]]


In [10]:
p = np.array(20)
a = np.array([10,20,30])
v = np.array([[10,20,30],[40,50,60]])
n = np.array([[[10,20,30],[40,50,60],[70,80,90]]])
print(p.ndim)
print(a.ndim)
print(v.ndim)
print(n.ndim)


0
1
2
3


In [11]:
arr = np.array([10,20,30,40], ndmin=8) #here i gave 8D.
print(arr)


[[[[[[[[10 20 30 40]]]]]]]]


In [12]:
print("Number of dimensions :", arr.ndim)


Number of dimensions : 8


In [13]:
arr = np.array([10,20,30,40])
print(arr[0])


10


In [14]:
arr = np.array([[10,20,30,40,50],[60,70,80,90,100]])
print(arr[0:2])
print("5th element on 2nd row: ", arr[1, 4])


[[ 10  20  30  40  50]
 [ 60  70  80  90 100]]
5th element on 2nd row:  100


In [19]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0,1,2])
print(arr[1,1,0])
print(arr[1,0,2])


6
10
9


In [20]:
arr = np.array([[10,20,30,40,50],[60,70,80,90,100]])
print(arr[1,-1])

100


In [21]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[2:5])


[3 4 5]


In [22]:
print(arr[:5])
print(arr[-4:-1])
print(arr[-6:-1])


[1 2 3 4 5]
[4 5 6]
[2 3 4 5 6]


In [23]:
arr = np.array([10,20,30,40,50,60,70,80,90])
print(arr[1:5:2])
arr[::1]


[20 40]


array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [25]:
arr = np.array([[10,20,30,40,50],[60,70,80,90,100]])
arr[1,2]
arr[0:2,2]


array([30, 80])

In [26]:
arr[0:2,1:4]


array([[20, 30, 40],
       [70, 80, 90]])

In [28]:
arr = np.array([6,4,7,4,7,5])
arr.dtype

dtype('int32')

In [29]:
arr = np.array(['pineapple','guava','mango'])
arr.dtype
arr = np.array([1,2,3,4,5], dtype="S") #For i, u, f, S and U we can define size as 
print(arr)
arr.dtype
arr = np.array([1, 2, 3, 4], dtype='i4')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4' b'5']
[1 2 3 4]
int32


In [31]:
arr = np.array([1.1, 2.1, 3.1])
arr.astype('i')

array([1, 2, 3], dtype=int32)

In [32]:
arr = np.array([1.1, 2.1, 3.1])
arr.astype(int)

array([1, 2, 3])

In [36]:
arr1 = np.array([1,3,5,8,9])
x = arr1.view()
arr1[2]=99
print(arr1)
print(x)


[ 1  3 99  8  9]
[ 1  3 99  8  9]


In [37]:
x= arr1.copy()
y = arr1.view()
arr1[3] = 1000
print("X is:", x)
print(y)


X is: [ 1  3 99  8  9]
[   1    3   99 1000    9]


In [38]:
arr2 = np.array([[12,34,56,75],[76,85,26,86]])
print(arr2.shape)

(2, 4)


In [39]:
arr = np.array([[3,6,8,5,4,],[6,4,6,2,4]])
for x in arr:
    for k in x:
        print(k)

3
6
8
5
4
6
4
6
2
4


In [40]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for p in arr:
    for v in p:
        for k in v:
            print(k)

1
2
3
4
5
6
7
8
9
10
11
12
